KEY_SIZE = 32  # AES-256
NONCE_SIZE = 12
SALT_SIZE = 16
GCM_TAG_SIZE = 16
WIPE_PASSES = 1
WIPE_CHUNK_SIZE = 64 * 1024

AUTH_FILE_NAME = ".auth"
AUTH_VERSION = 1
AUTH_MODE_PASSWORD_KEYFILE = "password_keyfile"

KDF_ITERATIONS = 3
KDF_MEMORY_COST = 2**16  # 64 MB
KDF_LANES = 4

MIN_KEYFILE_SIZE = 32
